{% set version = "1.1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sigclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sigclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sigclust/sigclust_{{ version }}.tar.gz
  sha256: eacdb4b5598e64722e515e749a3ff3dc14e8a296836afdd0a17ab153a96a72e0

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sigclust')"  # [not win]
    - "\"%R%\" -e \"library('sigclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sigclust
  license: GPL-2.0-or-later
  summary: SigClust is a statistical method for testing the significance of clustering results. SigClust can be applied to assess the statistical significance of splitting a data set into two clusters. For more than two clusters, SigClust can be used iteratively.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
