travis:
  secure:
    BINSTAR_TOKEN: irKDx7mI4wtHUnn9j3qn0coE6NQ9lAuOS/U9hstdnDx57NzviaWG67Q2TLph7rAA9qPQollwawG9DkJ/ErnwEAGXGGJ7HN3HqkvbV5TxacMSREyWsvDQ2sNhBjRXlX5I2kfFXz8oDEflxQpHAeGfnSKD848YozujKtsEhJyCCa6oligO4klpAkOzKG740JVKDteT3fCqcOWJGNU9c2acp9+fZCSuM5HEZqwopMdyr3PJOwCbc1OG68E48JN9fL9EsUdYsrJinc1KcS7OVUf4y61JGXCnm6tmPlmdla3RS6aTIsHaZdMFZquUuJLP+7pXIHmpBeK1X8SuT2IUS4HvUjwDfJwQF38lXcTud1jwWUMQMkinVW2EUIlgVDH+Kgmg0cGZhhr5USXGZn7X0bK1px68atRcAQ4aU9MDt9zMJFlzfr2mkxl5mZuHR+y+jyrHv/aydp36OnZFhkts3qti0JMzdO66AoD2XV4nJfvcANkQcfZWX7e4mB41dmFV4VZS89ST3i0/Mv7kmXpX4QBsV1qLbVsPuhxbP/R0LndpIrW3GjoIZs/mU2VKYFZY2D/uIwQJ/9odPIELJM//BA4kkLFjtKIjZ/d7xRcbYyN8a3LQZwnhBOT+WBtL+501bz4oj72FFsqtgM+DHJuXqMNQealg2Qps18Hf9xj0utj+CQI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
